spring.datasource.url=jdbc:postgresql://localhost:5432/gestao_vagas
spring.data.username=guilhermelimadesouza
spring.data.password=202520
spring.datasource.driver-class-name=org.postgresql.Driver

# Keeps Spring from attempting to initialize JPA before the DataSource is ready
spring.jpa.hibernate.ddl-auto=update

security.token.secret=JAVAGAS_@123#
security.token.secret.candidate=JAVAGAS_@123#CANDIDATE